# Generated by Django 2.2.1 on 2019-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190602_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='content',
            field=models.CharField(default='abc', max_length=25),
        ),
    ]
