# Generated by Django 2.2.1 on 2019-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_msg_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='msg',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
